server:
  port: 8421

spring:
  # 配置Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 128kb
      batch-size: 131072
      # 64M
      buffer-memory: 67108864
      # max-request-size: 5242880
      # linger-ms: 5
      retries: 1
      acks: 0
      # 提升性能很重要
      compression-type: gzip
      properties:
        # 5M
        max.request.size: 5242880
        linger.ms: 5
    consumer:
      -auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 3000

  cloud:
    nacos:
      discovery:
        # 启用使用Nacos进行服务发现
        enabled: true
        server-addr: localhost:8848
        namespace: 5656fc4e-ab3e-4983-a653-3d52f0c542c8

      config:
        # 启用使用Nacos进行配置管理
        enabled: true
        server-addr: localhost:8848
        # 此应用程序的Nacos配置组
        group: DEFAULT_GROUP
        namespace: 5656fc4e-ab3e-4983-a653-3d52f0c542c8

  # 配置Redis
  redis:
    host: localhost
    port: 6379

  # 数据库配置
  datasource:
    #druid配置
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/trans?useUnicode=true&characterEncoding=utf8
      username: root
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false